global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#otus-project-2020-02'
