version: '3.3'

services:
  prometheus:
    image: ${MYUSERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - frontend-network
      - backend-network

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - frontend-network
      - backend-network

  mongodb-exporter:
    image: ${MYUSERNAME}/mongodb-exporter:v0.11.0
    networks:
      - backend-network
    environment:
      MONGODB_URI: 'mongodb://crawler_db:27017'

  blackbox-exporter:
    image: ${MYUSERNAME}/blackbox-exporter:latest
    ports:
      - '9115:9115'
    networks:
      - frontend-network
      - backend-network

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - frontend-network
      - backend-network

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - frontend-network
      - backend-network

  alertmanager:
    image: ${MYUSERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - frontend-network
      - backend-network

volumes:
  crawler_db:
  prometheus_data:
  grafana_data:

networks:
  frontend-network:
  backend-network:
