plugin: gcp_compute
projects:
  - otus-project-2020
zones:
  - "europe-west1-b"
auth_kind: serviceaccount
service_account_file: /home/eugenebbr/key.json
groups:
  gitlab-ci-instance: "'stage-gitlab-ci-instance' in name"
hostnames:
  - name
filters:
  - labels.environment = "stage"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
